### ISSUE TITLE
Review <maintenanceStatus> values in EAD context - do they make sense?

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#104]
Values include the following: revised, deleted, new, deletedSplit, deletedReplaced, cancelled, derived.

I think revised, deleted, new, and derived make sense in an EAD context. 

@dpitti - do you see how deletedSplit, deletedReplaced, or cancelled might with for EAD?  

If those values don't work for EAD, do we strike them or keep them for consistency with EAC?

**Comment by kshepher** [comment]
Text similar to that used for EAC has been incorporated into the Tag Library.
