### ISSUE TITLE
Usage of @localType should be clarified

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#158]
2) In general, it does not seem like @localType is being implemented  
according to EAC-CPF specifications, which indicates that the value must be a  
URI or otherwise defined in `<localTypeStructured>`.

Submitted on Thursday, April 25, 2013 - 4:02pm
Submitted values are:

Name:  Julie Hardesty
Affiliation: Indiana University EAD Working Group
Does this represent an official comment from your affiliated group? Yes

**Comment by kshepher** [comment]
@rockivist Could you clarify the documentation need here? Is it just to specify that, indeed, @localtype in EAD isn't following the EAC model? Thanks.

**Comment by tcatapano** [comment]
@kshepher, @rockivist: I'd recommend adopting the CPF language, but
changing what is said about URIs, here is an inelegant stab at it, which at
least gets at most of the issues...

Summary:

Used to make the semantics of the element more specific or to provide
semantic specificity to elements that are semantically weak.

Description:

The localtype attribute is intended to provide a means to narrow the
semantics of some elements or provide semantics for elements that are
primarily structural or that are semantically weak. The value of the
localtype may be from a local or generally used external vocabulary. While
the value of localtype may be any string, to facilitate exchange of data,
it is recommend that the values be either the URI or the preferred label
for a term defined in a formal vocabulary (e.g., SKOS) which is identified
by an absolute URI, and is resolvable to a web resource that describes the
semantic scope and use of the value.

**Comment by rockivist** [comment]
@kshepher I like what @tcatapano suggests.  The crucial piece was to remove the URI requirement and clarify why.

**Comment by kshepher** [comment]
Thanks! The attribute section doesn't separate Summary and Description, so I just used the one paragraph and made some very minor tweaks to try to make it more readable:

@localtype  Local Type                   	
An optional attribute allowing a general type to be recorded for local use. This attribute is intended to provide a means to narrow the semantics of an element, or provide semantics for elements that are primarily structural or semantically weak. The value of @localtype may be from a local or generally used external vocabulary. While the value of @localtype may be any string, to facilitate exchange of data, it is recommended that the value beith either the URI or the preferred label for a term defined in a formal vocabulary (e.g., SKOS), which is identified by an absolute URI, and is resolvable to a web resource that describes the semantic scope and use of the value. 


I'm closing the ticket, but reopen or edit the TL if you're not happy with this.
