### ISSUE TITLE
Whither extptr and extref?

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#171]
Have `<extptr>` and `<extref>` been dispensed with?  What type of linking  
mechanisms is available if we're not linking to digital representations from  
the collection?

Submitted on Monday, April 29, 2013 - 10:54am
Submitted values are:

Name: Mark Carlson
Affiliation: University of Washington
Does this represent an official comment from your affiliated group? No

**Comment by kshepher** [comment]
<ptr> and <ref> to be used for both internal and external links. TL includes this in description for these elements.
