### ISSUE TITLE
Where to encode URIs for collections (not descriptive records)?

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#174]
Submitted on Monday, April 29, 2013 - 12:21pm
Submitted values are:

Name: Kate Bowers
Affiliation: Harvard Library
Does this represent an official comment from your affiliated group? Yes
Comment:
We are wondering where URIs for collections themselves (and components  
themselves) might be recorded in revised EAD. The XML @id attribute does not  
like colons in its values according to oXygen validation.

Just to be clear, URIs for _descriptive records_ for collections seem to be  
quite handily accommodated by the existing schema otherRecordId element  
(thanks!), and we'd hope to see this element available as a child of `<c>` as  
well.

The results of this submission may be viewed at:
http://www2.archivists.org/node/17190/submission/13103

**Comment by kshepher** [comment]
Added example.
