### ISSUE TITLE
Why is the script attribute in every child element of <control>?

### ISSUE THREAD

**Issue by ksferrante** [SAA-SDT/EAD-Revision#258]
Question from the EAD Hackathon

Why is the script attribute in every element? We could understand the use case in the description sections but had a hard time imagining a use case for defining differing scripts within <control>.

**Comment by kshepher** [comment]
@rockivist: Is current language sufficient?

@lang  Language                          	
Indicates the language of the content of an element.  Content of the attribute should be a code taken from ISO 639-2b. May be used consistently in a multi-lingual finding aid to specify which elements are written in which language. Available on all non-empty elements.

@script  Script                           	
Indicates the writing script of the content of an element. May be used consistently in a multi-lingual finding aid to specify which elements are written in which script. Available on all non-empty elements.

**Comment by rockivist** [comment]
@kshepher No. The definition for `@lang` in particular needs to be revised. We loosened the schema to mention other ISO code lists.  See `@langencoding` on `<control>` for the options. I think we can reommend 639-2b, but we should mention the others, and also allow for alternative codes to be used in conjuction with langencoding="otherlangencoding".

**Comment by kshepher** [comment]
Thanks for the clarification. TL updated to include the broader list of options, and to make the relationship between @lang and @langencoding more apparent.
