### ISSUE TITLE
<languageset> 2 languages and 2 scripts

### ISSUE THREAD

**Issue by ksferrante** [SAA-SDT/EAD-Revision#262]
Languageset allows you to put in several scripts and several languages together indiscriminately.  There could be two languages in one scripts or one language in two scripts. But the ability to put two languages and two scripts could be confusing.

Here's an example: 
<languageset>
                    <language langcode="eng"/>
                   
                    <language  langcode="ger" lang="eng">German</language>
                 
                    <script scriptcode="latnf"/>
                    <script scriptcode="latn"/>
</languageset>

**Comment by rockivist** [comment]
Addressed in TL. Closing.
