### ISSUE TITLE
Clarify relation of custodhist and acqhist now that they no longer nest

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#313]
Submitted on Friday, September 27, 2013 - 1:28am
Submitted values are:

Name:  Nicola Frean
Affiliation: Alexander Turnbull Library, National Library of New Zealand
Does this represent an official comment from your affiliated group? No
Comment:
These comments are based on a brief group discussion around Michael Rush's  
eamils to the EAD listserv (thankyou Michael!):
1. Disentangling Descriptive Elements'
Is the last element of Custodhist automatically the same as immediate source  
of acquisition, or is it to be repeated?

**Comment by kshepher** [comment]
Description and see also references on both elements make usage clear in TL.
