### ISSUE TITLE
How best to describe born-digital materials?

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#318]
Submitted on Friday, September 27, 2013 - 1:28am
Submitted values are:

Name:  Nicola Frean
Affiliation: Alexander Turnbull Library, National Library of New Zealand
Does this represent an official comment from your affiliated group? No
Comment:
These comments are based on a brief group discussion around Michael Rush's  
eamils to the EAD listserv (thankyou Michael!):

We also had a question about the capability for growing amounts of  
information about born-digital material, for example, digital extent. I  
believe the tag phystech has capacity for digital information, but the tag  
name could perhaps reflect this better?

**Comment by kshepher** [comment]
@rockivist added examples for this.
