### ISSUE TITLE
Where to encode information about conservation treatments?

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#319]
Submitted on Friday, September 27, 2013 - 1:28am
Submitted values are:

Name:  Nicola Frean
Affiliation: Alexander Turnbull Library, National Library of New Zealand
Does this represent an official comment from your affiliated group? No
Comment:
These comments are based on a brief group discussion around Michael Rush's  
eamils to the EAD listserv (thankyou Michael!):

Lastly, we have been exploring the inclusion of information about  
conservation treatments and would welcome an example in EAD3 about where to  
best locate this - `<phystech>` or `<physfacet>`?

**Comment by kshepher** [comment]
Added conservation as an example of the kind of info to be included. Could add to examples as well.

**Comment by kshepher** [comment]
Added example.
