### ISSUE TITLE
Is there a preferred element for listing LCCN or other identifier for the bibliographic description of the collection?

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#339]
Submitted on Monday, September 30, 2013 - 2:02pm
Submitted values are:

Name:  Mary Lacy
Affiliation: Library of Congress
Does this represent an official comment from your affiliated group? Yes
Comment:
Library of Congress Comments on EAD 3 beta release, Sept. 30, 2013:

12.	Is there a preferred element for listing LCCN or other identifier for the  
bibliographic description of the collection? We’ve been using  
`<otherfindaid>`, but it can no longer accept `<ref>` directly. The Tag Library  
gives an example of a catalog record link under `<controlnote>`.

**Comment by kshepher** [comment]
TL updated to show link to catalog record as example in otherfindaid instead of control note.
