### ISSUE TITLE
How extensively should <conventiondeclaration> be used?

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#340]
Submitted on Monday, September 30, 2013 - 2:02pm
Submitted values are:

Name:  Mary Lacy
Affiliation: Library of Congress
Does this represent an official comment from your affiliated group? Yes
Comment:
Library of Congress Comments on EAD 3 beta release, Sept. 30, 2013:

14.	Is `<conventiondeclaration>` meant to be used as widely as seems to be  
specified? (That is, not only descriptive rules such as DACS, RDA, and AACR2,  
but also multiple thesauri, such as AAT, TGM, and LCSH? This could need to be  
an extensive section to template into EAD instances.

**Comment by kshepher** [comment]
The element is optional, and current TL language tries not to be prescriptive, but to describe how it could be used.
