### ISSUE TITLE
Provide guidance on use of <materialspec>

### ISSUE THREAD

**Issue by anarchivist** [SAA-SDT/EAD-Revision#344]
In EAD 2002, `<materialspec>` was understood in part to map to MARC fields [254](http://www.loc.gov/marc/bibliographic/bd254.html), [255](http://www.loc.gov/marc/bibliographic/bd255.html), and [256](http://www.loc.gov/marc/bibliographic/bd256.html). In my opinion, the type of data that appears in a 256 field is probably better expressed in `<extent>`. I'm curious if our work on the geographic elements somehow addresses some of the needs to map geographic information that would be expressed in a 255 field.

(copied from #297)

**Comment by kshepher** [comment]
Looking at the MARC examples for 256 reinforces the point about field 256, and I've changed the mapping. The addition of the geographiccoordinates element accommodates 255$c, but not the other contents of 255, so I've split that up in the crosswalks for both MARC and MODS.
