### ISSUE TITLE
Use hyperlinks among element/attribute definitions in the official tag library

### ISSUE THREAD

**Issue by bencomp** [SAA-SDT/EAD-Revision#355]
It would increase the ease of use of the official tag library if mentions of allowed tag and attribute names were links to their definition.

Each element and attribute has a definition, and/or references to other elements and attributes that it can appear in or can appear in it. The current tag libraries (HTML and PDF at loc.gov) do not have links for these references, which makes navigation unnecessarily difficult.

(This appears to have been mentioned a lot in the EAD survey.)

**Comment by kshepher** [comment]
The online Tag Library will be fully linked, as the EAC TL is.
