### ISSUE TITLE
Modify controlaccess elements for linked data applications

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#374]
Per TS-EAD compromise re: `<relations>` we decided to modify all of the controlaccess elements (see m.access) so that they provide sufficient attributes to support a lightweight linked data application.

@tcatapano and I discussed this and we identified the following components as the minimum necessary for creating LD triples:

Subject: The thing being linked from.
Predicate: a relator term.
Object: The resource being linked to.

In the context of EAD, the subject is the nearest ancestor c or archdesc.  The object is the resource being linked to (the term embedded in the persname, for example, and it's authority file record as represented by `@identifier`.

There are predicates already explicit in some EAD contexts (subject, for example), but it is necessary to provide a more precise option for including a URI for a relator term from an external vocabulary.  This essentially provides two potential predicates, one in which the element name is the predicate, one in which the relator term is the predicate.

The conclusion we arrived at is that each controlaccess element should have the following attributes:
`@source` [URI or string for name of vocabulary from which term is taken]
`@rules' [URI or string for rules by which term is devised]
`@identifier` [URI or string for the term]
`@relator` [URI or string for a relator term, a migration path for `@role` from EAD 2002]
`@localtype` [URI or string for any other local subclassing]

We wanted to avoid using xlink attributes as we didn't think these elements should be links in the traditional sense, and the xlink spec's definitions for `@role` and `@arcrole` are overlapping.  This solution also eliminates the semantic collision in EAD 2002 between `@role` on controlaccess elements and and `@xlink:role` on linking elements.

**Comment by kshepher** [comment]
Verified documentation.
