### ISSUE TITLE
Remove pattern validation for date normalization attributes

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#380]
See #368 for the thread that originated this suggestion.

We have already removed hard-coded validation lists (i.e. for language codes), both because those code lists are updated more frequently than EAD, but also because it would allow people to use alternative code lists when appropriate.

Removing date normalization attribute patterns would fit with the second rationale and allow people to use alternative machine-processable date formats.  There are a lot available, actually, such as ISO 8601, a profile of ISO 8601 such as W3Cdtf, xs:date, or most significantly EDTF.

We can (and will) supply an external schematron for those who wish to continue to validate date normalization attributes with ISO 8601.  We could also create schematrons for validation in other date formats.

The following attributes would be affected:
`@normal`
`@lastdatetimeverified`
`@standarddate`
`@notbefore`
`@notafter`
`@standarddatetime`

**Comment by kshepher** [comment]
@rockivist Where do you think it's best to incorporate information about using schematron to validate content within the TL? Within each of the relevant elements, in a preface, both?

**Comment by rockivist** [comment]
@kshepher I think the preface needs to address in detail the validation functionality that has been removed to Schematron. Individual tag definitions should for the most part stick to what is represented in the schema.  We'll keep the schematron documentation mostly online - it will evolve over time too much for it to be incorporated into the print Tag Library.

**Comment by kshepher** [comment]
That was my feeling as well. I'll leave this open to make sure it gets into the preface.

**Comment by rockivist** [comment]
@tcatapano There is a problem in the schema re: this issue. We intended to remove the date normalization pattern from all of the attributes listed above in my first comment on the issue. However, as it stands now, the only attribute for which the pattern has been removed is `@normal`. Unless I am failing to remember a conversation and justification for why we should keep the pattern on the others, we need to revise the schema to convert those other attributes to token like `@normal`, and update the schematron to provide the appropriate pattern validation. 

When updating the schematron, remember that the patterns for `@notafter`, `@notbefore`, and `@standarddate` don't include the time, but `@lastdatetimeverified` and `@standarddatetime` do.  And all of these omit the / range pattern from 8601 that is included in `@normal`.

@kshepher For now I have updated the TL to reflect how the schema currently stands. When Terry corrects the schema we can update then.

**Comment by tcatapano** [comment]
@rockivist my guess is that the patterns exist in the elements drawn from EAC-CPF and were retained. While I think it is better to remove the patterns from attributes of elements under `<archdesc>`, wouldnt it be best for values of dates and times in `<control>` to be, well, controlled?

**Comment by ruthtillman** [comment]
@tcatapano I agree it makes sense to control at the least what's in control, esp if reflecting EAC-CPF. Was there a reason this would be too much of a burden for end users?

**Comment by rockivist** [comment]
@tcatapano Yes, you're exactly right that the patterns persist in the EAC-CPF elements. Following your logic, we should keep the pattern validation on `@standarddatetime` and `@lastdatetimeverified` but remove it from `@notbefore`, `@notafter`, and `@standarddate`. It's not a perfect divide between control and archdesc, but it's pretty close.

Sound good?

@ruthtillman The decision to remove pattern validation for date normalization attributes was in response to community requests to allow alternative date normalization schemes.

**Comment by tcatapano** [comment]
`@notbefore`, '@notafter`, and `@standarddate` now have datatype token. `@standarddatetime` and `@lastdatetimeverified` unchanged

**Comment by rockivist** [comment]
TL updated. See #472 re: adding patterns to schematron. Closing.
