### ISSUE TITLE
Use of <daoset> for thumbnails embedded in finding aids?

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#400]
Submitted on Friday, February 28, 2014 - 2:33pm
Submitted values are:

Name:  Kate Bowers
Affiliation: Harvard University Library
Does this represent an official comment from your affiliated group? Yes
Comment:
Use of `<daoset>` for thumbnails embedded in finding aids?

I wasn't sure if `<daoset>` was envisioned as the mechanism for embedding  
thumbnails with links to resources in EAD.  I assume a clever stylesheet  
could turn the following example into an embedded image that becomes a  
clickable link to the resource.

`<daoset coverage="whole">
     <dao daotype="other"  
href="nrs.harvard.edu/urn-3:HUL.ARCH:kate?height=250" localtype="thumbnail"  
show="embed">
         <descriptivenote>
             <p>Full size image is available online.</p>
         </descriptivenote>
     </dao>
     <dao daotype="borndigital"  
href="nrs.harvard.edu/urn-3:HUL.ARCH:kate?buttons=y"/>
</daoset>`

The results of this submission may be viewed at:
http://www2.archivists.org/node/17190/submission/15485

**Comment by kshepher** [comment]
Need example of a <daoset> with two <dao>s - one with localtype set to thumbnail, another with fullsize or some other local terminology.

**Comment by kshepher** [comment]
Example included in TL.
