### ISSUE TITLE
Add @role to <function>, supply relationship vocabulary

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#408]
Submitted on Friday, February 28, 2014 - 8:45am
Submitted values are:

Name: Karsten Kühnel
Affiliation:
Does this represent an official comment from your affiliated group? No
Comment:
1.	Element `<function>`, attribute `@role` and relationships
The element `<function>` is described in the Gamma Schema for EAD Revision by  
the beta release description yet. I would be happy if also for `<function>` the  
attribute `@role` would become available. Here ad minimum the relationships  
should be able to be described which you can find in the ICA paper  
“Relationships in archival descriptive systems”; e.g. between functions  
and records: creator of/created by; subject of/concern; controller  
of/controlled by. Additionally I suggest to insert the relationship “user  
of/used for”. The last one might be interesting if records have been  
re-used for another function than the function that was responsible for the  
creation of the records (de- and re-contextualisation of records during their  
life cycle). Further there should be found the usual relationships like, for  
example, compiling and collecting.

The results of this submission may be viewed at:
http://www2.archivists.org/node/17190/submission/15476

**Comment by kshepher** [comment]
Incorporated into TL.
