### ISSUE TITLE
Will there be clear rules as to how to apply <part>?

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#412]
Submitted on Friday, February 28, 2014 - 2:32pm
Submitted values are:

Name: Ronda L. Sewald
Affiliation: Indiana University
Does this represent an official comment from your affiliated group? No
Comment:

Will there be clear rules as to how to apply `<part>` for wrapping authorized  
headings (e.g., the entire heading versus multiple tags around a name,  
qualifier, dates, etc.)? This would assure consistent application across  
institutions.

The results of this submission may be viewed at:
http://www2.archivists.org/node/17190/submission/15484

**Comment by kshepher** [comment]
Addressed in text and included multiple examples.
