### ISSUE TITLE
Need <materialspec> example re: music records

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#418]
Submitted on Friday, February 28, 2014 - 2:32pm
Submitted values are:

Name: Ronda L. Sewald
Affiliation: Indiana University
Does this represent an official comment from your affiliated group? No
Comment:

For `<materialspec>`, the description states that it can be used to record  
information about the “physical presentation data for music records,” but  
even as an audiovisual/music cataloger, I'm not sure what this means or how  
to apply it. Can you supply an example?

The results of this submission may be viewed at:
http://www2.archivists.org/node/17190/submission/15484

**Comment by kshepher** [comment]
Score example draw from MARC 254.

**Comment by MicheleCombs** [comment]
I think I included one of these in the examples I sent you, Kelcy.
