### ISSUE TITLE
Remove @linktype?

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#432]
Now that we have removed all non-simple links from EAD, do we need to keep `@linktype` in the schema?  I see no functional reason to do so.  The only argument I can see is for careful compatibility with xlink.  I note that EAC-CPF only includes simple links, but still carries `@xlink:type`.  See http://www3.iath.virginia.edu/eac/cpf/tagLibrary/cpfTagLibrary.html#xlinktype.  

@tcatapano - what do you think?  This came up from the tag library editorial team.

**Comment by kshepher** [comment]
Thanks, @rockivist. I'll leave this open, then.

**Comment by rockivist** [comment]
Addressed in TL preface. Closing.
