### ISSUE TITLE
`@char` and `@charoff` should be in `<tgroup>`?

### ISSUE THREAD

**Issue by ruthtillman** [SAA-SDT/EAD-Revision#444]
Now that `@align` has the possible value of "char" again, should `@char` and `@charoff` be added to `<tgroup>`, since it has `@align`? Otherwise one might set the value to "char" but not be able to add the data for it. Or should it just be left as is because it's kind of meaningless and should be set in `<colspec>` anyway?

Right now, `<colspec>` and `<entry>` are the only places where those two attributes can be used.

Just throwing it out as I update EADiva to match the revisions to table.

**Comment by rockivist** [comment]
@tcatapano This didn't make it into ead_revised_defs.rng. Can you re-add?

**Comment by rockivist** [comment]
@tcatapano Actually - wait on this.  Let's discuss on Friday. Looking at this again I'm changing my mind and I think it might be better left as it was in EAD 2002.

**Comment by tcatapano** [comment]
Discussed and decided to not include in EAD3.
