### ISSUE TITLE
schematron: lang codes

### ISSUE THREAD

**Issue by tcatapano** [SAA-SDT/EAD-Revision#466]
Need to find an xml version of iso639-3; address otherlangencoding case; remove default of iso6392?

**Comment by tcatapano** [comment]
What is the desired functionality for otherlangencoding? It's very difficult to come up with a rule and tests for it generally.

**Comment by tcatapano** [comment]
Has it been decided to remove iso639-2b as the default?

**Comment by rockivist** [comment]
@tcatapano Re: otherlangencoding - I don't think the schematron needs to do anything regarding it. If someone wants to use another language code list beyond the three we include, they can figure it out.

Re: iso639-2b, yes, we can assume that is still the default. If there is no `@langencoding` on `<control>` then we should validate against iso639-2b.

**Comment by tcatapano** [comment]
Think this is closed
