### ISSUE TITLE
Inconsistent data types on "otherATTRIBUTENAME" attributes

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#468]
During my TL attribute review I noticed that the various "otherATTRIBUTENAME" attributes have inconsistent data types. They are as follows:

otherdaotype - none
otherphysdescstructuredtype - none
otherdsctype - NMTOKEN
otherrelationtype - string
otherlevel - NMTOKEN

@tcatapano I think this merits a change to the schema to bring them into alignment. I'm thinking token is the best option here. What do you think?

I'm tagging @kshepher on this too so that we remember to update the TL when the change is in.

**Comment by rockivist** [comment]
For the record I have updated the TL to reflect how it currently stands.

**Comment by tcatapano** [comment]
@rockivist I agree that token is probably the way to go. I'm having a hard time coming up for a reasonable argument for permitting the extra whitespace allowed by string and normalizedString.

**Comment by rockivist** [comment]
@tcatapano OK. Implement it when you can.

**Comment by tcatapano** [comment]
Implemented. Closed.
