### ISSUE TITLE
model for list

### ISSUE THREAD

**Issue by tcatapano** [SAA-SDT/EAD-Revision#470]
Is this really what is intended?

`<!ELEMENT list (head?,(item+|(listhead?,defitem+)))>`

That is, an optional head, followed by one or more items OR an optional listhead followed by one or more defitems.

FWIW, this is how it is in EAD 2002.

The Tag Library says this about `<listhead>`: "A formatting element that groups headings for columns in a definition, unordered, or ordered list..." But the model only permits its use in a definition list. Also, in `<chronlist>` it is easy to imagine "date" "place" and "event" headings, but what would be an example of the use of `<head03>` in a `<list>` under the current model?

Seems like either the model needs revision or the Tag Library needs to be clearer.

**Comment by dpitti** [comment]
It would not make sense, that is, unless you have changed <defitem> for EAD3, as a column head for a third column would not make sense in a <list> containing a series of <defitem>. Answering the very last question.

**Comment by rockivist** [comment]
@tcatapano @dpitti We added `<head03>` to `<listhead>` for use in `<chronlist>` to give headings for `<geogname>`, which are now included in the model along with events and dates.  That does mean that `<head03>`

**Comment by rockivist** [comment]
TL updated. Closing.
