### ISSUE TITLE
add license, documentation to schema?

### ISSUE THREAD

**Issue by tcatapano** [SAA-SDT/EAD-Revision#473]
If so, which license, what information?

**Comment by rockivist** [comment]
Add the CC0 license, which we agreed to add to all code for EAD3. I believe it is already in the migration style sheet.

What documentation do you think we need in the schema?

**Comment by rockivist** [comment]
@tcatapano Is there an issue with using the same CC0 license as you added to the migration style sheet? I think a simple reference and link to the license is sufficient. It should be in the introductory comment.

**Comment by tcatapano** [comment]
Added CC 1.0 Universal license file. Closing.
