### ISSUE TITLE
In EAD3 undeprecated, fix extent attributes

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#474]
Add am.common, a.label, a.encodinganalog, and a.localtype models, then create attribute `@unit`, as optional, token.

**Comment by tcatapano** [comment]
Implemented. Closed.

**Comment by rockivist** [comment]
@tcatapano You missed adding `@unit` to extent in the undeprecated driver. Reopening.

**Comment by tcatapano** [comment]
Implemented. Closing.
