### ISSUE TITLE
Add imprint to bibref in undeprecated EAD3

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#476]

**Comment by MicheleCombs** [comment]
Hm, I'm beginning to wonder if Kelcy and I are jumping the gun on validating examples for the tag library. I just finished taking imprint out of a bunch of them.


Michele

________________________________

**Comment by rockivist** [comment]
@MicheleCombs imprint and bibseries (along with all deprecated elements) should absolutely be removed from all examples in the main section of the tag library. They will only exist in the undeprecated version of EAD3, and will only have examples in Appendix B, which I am working through. So full speed ahead with examples validated against the main schema.

**Comment by MicheleCombs** [comment]
Ah yes – I missed the key word “undeprecated” – sorry!

Michele
