### ISSUE TITLE
Add agencycode to code-list checks in schematron?

### ISSUE THREAD

**Issue by tcatapano** [SAA-SDT/EAD-Revision#477]

**Comment by rockivist** [comment]
Yes, add the pattern from EAC-CPF that we elected to remove.  Here it is: 

`<param name="pattern">(([A-Z]{2})|([a-zA-Z]{1})|([a-zA-Z]{3,4}))(-[a-zA-Z0-9:/\-]{1,11})</param>`

**Comment by tcatapano** [comment]
Should I use the text from the AgencyCode element description in the EAC-CPF Tag Library in the error message: "The format of the code is constrained to that of the International Standard Identifier for Libraries and Related Organizations (ISIL: ISO 15511): a prefix, a dash, and an identifier. "?

**Comment by rockivist** [comment]
@tcatapano Sounds good to me.

**Comment by rockivist** [comment]
Looks good. Closing.
