### ISSUE TITLE
Values for @mark and @numeration

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/EAD-Revision#478]
It seems contradictory that we have the values "upperalpha", "loweralpha", "upperroman", "lowerroman" for @numeration with ordered lists as well as for @mark with unordered ones. Might be an idea to separate these.

Also, as this is supposed to be aligned with CSS, the values should be used with a hyphen.

**Comment by MicheleCombs** [comment]
Agree.  Unordered lists by definition don’t have letters or numbers, otherwise they become ordered lists.

**Comment by rockivist** [comment]
@kerstarno Thanks for spotting this. 

@tcatapano Go ahead and implement. I have updated the tag library to reflect the following:

`@mark` values: disc, circle, square, none, inherit

`@numeration` values: decimal, decimal-leading-zero, lower-roman, upper-roman, lower-greek, lower-latin, upper-latin, armenian, georgian, lower-alpha, upper-alpha, inherit

**Comment by tcatapano** [comment]
implemented.
