### ISSUE TITLE
Write introductory comment to include in EAD3 schemas

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#483]
Need to write some acknowledgements, probably some technical advice.

**Comment by rockivist** [comment]
@tcatapano Just emailed a draft of an introductory comment to you. Assigning this to you.

**Comment by tcatapano** [comment]
Include names of TS-EAD and SDT members?

**Comment by rockivist** [comment]
@tcatapano Yes, include the names of TS-EAD and SDT members. The list as included in the Tag Library is as follows:

TS-EAD members during the revision process included Mike Rush, co-chair, Yale University; Bill Stockting, co-chair, British Library (UK); Kerstin Arnold, Bundesarchiv (Germany); Michael Fox, Minnesota Historical Society; Kris Kiesling, University of Minnesota; Angelika Menne-Haritz, Bundesarchiv (Germany); Kelcy Shepherd, University of Massachusetts and Amherst College; Claire Sibille, Direction Générale des Patrimonies (France); Henny van Schie, Nationaal Archief / Bibliotheek (Netherlands); and Brad Westbrook, University of California, San Diego, and ArchivesSpace. Notable ex-officio contributors included Jodi Allison-Bunnell, Orbis Cascade Alliance (EAD Roundtable); Anila Angjeli, Bibliothèque nationale de France (TS-EAC); Hillel Arnold, Rockefeller Archives Center (EAD Roundtable); Mark Custer, Yale University (EAD Roundtable); Merrilee Proffitt, OCLC Research; Ruth Kitchin Tillman, Cadence Group (EAD Roundtable); and Katherine Wisser, Simmons College (TS-EAC). Schema Development Team members included Terry Catapano, chair, Columbia University; Karin Bredenberg, Riksarkivet of Sweden; Florence Clavaud, Ecole Nationale des Chartes (France); Michele Combs, Syracuse University; Mark Matienzo, Yale University and DPLA; Daniel Pitti, University of Virginia; and Salvatore Vassallo, Università degli Studi di Pavia (Italy).

**Comment by tcatapano** [comment]
I've added some text, reformatted, and included the text of the introductory info in the file RELEASE.md, which I think should be included in the release (and maybe in the master branch of the repo) rather than in each of the schema files.

**Comment by rockivist** [comment]
@tcatapano The RELEASE.md looks good. I fixed a few character encoding issues with accented vowels. Should we add the CC0 license as well?

**Comment by tcatapano** [comment]
Added license as it's own file. Closing.
