### ISSUE TITLE
Bug in schematron language code rule

### ISSUE THREAD

**Issue by rockivist** [SAA-SDT/EAD-Revision#487]
Getting the following bug when testing the schematron:

"System ID: C:\Users\mr498\Documents\GitHub\EAD-Revision\schematron\ead3.sch
Main validation file: C:\Users\mr498\Desktop\beinecke.hayward_ead3.xml
Engine name: ISO Schematron
Severity: fatal
Description: Required item type of first operand of '|' is node(); supplied value has item type xs:string
Start location: 234:0"

Problem seems to be in the `<rule>` for language codes.

**Comment by tcatapano** [comment]
Error is caused by the OR lookup against the iso_639_3.xml  file in the language-code-lookup variable. I'll need to figure out how to do the validation so that it includes is639-3. Removing support for it now.

**Comment by tcatapano** [comment]
This should now be fixed in develop.

**Comment by rockivist** [comment]
Looks good.

**Comment by tcatapano** [comment]
Closing.
