### ISSUE TITLE
Perform date validation only when dateencoding="iso8601"

### ISSUE THREAD

**Issue by tcatapano** [SAA-SDT/EAD-Revision#491]
The patterns for single date attributes as well as @normal on unitdate and date should only be enforced if control/@dateencoding="iso8601"

**Comment by tcatapano** [comment]
We didnt do this in the other cases where there was only one recommended encoding (e.g., scriptencoding and countryencoding). At this point, let's treat dateencoding the same.

**Comment by rockivist** [comment]
@tingletech Agreed. Closing.
